# Redis集群配置
spring:
  redis:
    # 集群配置
    cluster:
      # 集群节点列表
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      # 最大重定向次数
      max-redirects: 3
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
      # 集群拓扑刷新配置
      cluster:
        refresh:
          # 支持集群拓扑动态感应
          adaptive: true
          # 定时刷新集群拓扑，单位毫秒
          period: 30000
    # 连接超时时间
    timeout: 3000ms
    # 密码（如果集群设置了密码）
    # password: your_password

# 应用配置
app:
  redis:
    # 是否启用集群模式
    cluster-enabled: true
    # 集群健康检查间隔（秒）
    health-check-interval: 30
    # 故障转移超时时间（毫秒）
    failover-timeout: 5000
