# 服务配置
server:
  port: 21090
  servlet:
    context-path: /api/food-share-sys/v1.0
# API地址前缀，用于接口拦截放行
my-server:
  api-context-path: /api/food-share-sys/v1.0
#MySQL与文件上传限制配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_share?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: sx2002411
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
# 让 Mybatis 在 Mapper目录下找到 XML 映射文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名和下划线命名的转换

# 日志配置
logging:
  level:
    root: INFO
    cn.kmbeast: INFO
    cn.kmbeast.aop.CachingAspect: DEBUG
    cn.kmbeast.schedule.CacheWarmupScheduler: DEBUG
    cn.kmbeast.utils.RedisUtil: DEBUG
    cn.kmbeast.controller.RedisCacheTestController: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'




