# Redis集群配置
spring:
  redis:
    # 集群配置
    cluster:
      # 集群节点列表
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      # 最大重定向次数
      max-redirects: 3
    # Redis密码（如果设置了）
    # password: your_password
    # 连接超时时间
    timeout: 3000ms
    # 连接池配置
    lettuce:
      pool:
        # 高并发优化配置
        max-active: 100 # 增加最大连接数
        max-wait: 3000ms # 设置合理等待时间
        max-idle: 50 # 增加最大空闲连接
        min-idle: 20 # 增加最小空闲连接
        time-between-eviction-runs: 30000ms
      # 集群拓扑刷新配置
      cluster:
        refresh:
          # 支持集群拓扑动态感应
          adaptive: true
          # 定时刷新集群拓扑，单位毫秒
          period: 30000ms
      # 新增连接超时配置
      shutdown-timeout: 100ms

# 应用高并发配置
server:
  tomcat:
    threads:
      max: 200 # 最大线程数
      min-spare: 50 # 最小空闲线程数
    max-connections: 8192 # 最大连接数
    accept-count: 100 # 等待队列长度
    connection-timeout: 20000ms

# 应用配置
app:
  redis:
    # 是否启用集群模式
    cluster-enabled: true
    # 集群健康检查间隔（秒）
    health-check-interval: 30
    # 故障转移超时时间（毫秒）
    failover-timeout: 5000
  # 新增高并发配置
  performance:
    enable-async: true
    thread-pool-size: 50
    queue-capacity: 1000

# 日志配置
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
